In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a=np.array([5,6,7])

In [4]:
a

array([5, 6, 7])

In [5]:
a.shape

(3,)

In [6]:
a=np.array([[1,2,3],[4,5,6]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#gives us the dimension of the array
a.shape

(2, 3)

In [9]:
#this is gonna return what type of elements are present in the array
a.dtype

dtype('int64')

In [11]:
#returns how many rows are present in the numpy array
a.ndim

2

In [13]:
#type return what type
print(type(a))

<class 'numpy.ndarray'>


In [14]:
type([1,2,3])

list

In [27]:
#it returns a numpy array with all numbers from 0 to last-1
b = np.arange(100)

In [28]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
c = range(10000)

In [32]:
%timeit [i**3 for i in c]

1.98 ms ± 85.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [33]:
c_numpy = np.arange(10000)

In [35]:
#as we can see below that numpy is much faster
%timeit c_numpy**3

25.1 µs ± 660 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
l1 = range(10000)
l2 = [i**2 for i in l1]

In [39]:
%timeit list(map(lambda x,y:x*y, l1, l2))

797 µs ± 9.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [40]:
l1_numpy = np.array(l1)
l2_numpy = np.array(l2)

In [41]:
%timeit l1_numpy*l2_numpy

4.71 µs ± 67.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [42]:
#can even change the start and step
np.arange(2,10,2)

array([2, 4, 6, 8])

In [46]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
#creates an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
#want to completely fill any matrix with a perticular value
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [56]:
#you can ensure the data type you want
np.full((3,4),2.2, dtype=np.int)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [62]:
#to fill only the diagnol elements
z=np.diag([1,2,3,4,5])

In [72]:
#tile function lets you add rows and columns , np.tile(array_name,(row,col))
b = np.array([1,2,3])
np.tile(b,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [77]:
#return a random value between 0 and 1
np.random.random()

0.6002861290339788

In [79]:
#can also be used to create a matrix with random values
np.random.random((3,2))

array([[0.69092657, 0.61682606],
       [0.8886194 , 0.04419954],
       [0.36362276, 0.21854763]])

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a[2,2]

9

In [7]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
a[(a>2) & (a<5)]

array([3, 4])

In [12]:
#in numpy array even if u assign an array , then you are just pointing to same location
a=np.arange(10)
a
b=a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b[0]=11
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [16]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [18]:
#to check if a and b share memory or not
np.shares_memory(a,b)

True

In [19]:
#to make a seperate copy and not share memory
a=np.arange(10)
b=a.copy()

In [22]:
np.shares_memory(a,b)

False

In [48]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
#transpose the matrix
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b = np.array([[7,8,9],[10,11,12]])

In [34]:
a == b

array([[False, False, False],
       [False, False, False]])

In [36]:
#stack one array on top of other
np.vstack((a,b))

array([[ 1,  1,  1],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
#stack one array on other horizontally
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [53]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [54]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [55]:
np.sum(a)

21

In [56]:
np.median(a)

3.5

In [58]:
np.std(a)

1.707825127659933

In [60]:
a.std()

1.707825127659933

In [71]:
a=np.arange(1,10).reshape(3,3)

In [72]:
a[2,1]=19
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 19,  9]])

In [73]:
np.linalg.det(a)

65.99999999999997

In [74]:
np.linalg.inv(a)

array([[-1.04545455,  0.59090909, -0.04545455],
       [ 0.09090909, -0.18181818,  0.09090909],
       [ 0.62121212, -0.07575758, -0.04545455]])

In [75]:
np.linalg.eig(a)

(array([19.48487558, -0.96131146, -3.52356411]),
 array([[-0.18948186, -0.84658431, -0.36973813],
        [-0.4199663 ,  0.03339919, -0.41253218],
        [-0.88753869,  0.53120571,  0.83253283]]))

In [77]:
b = np.arange(1,10).reshape(3,3)
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [146, 181, 216]])

In [79]:
a=np.array([1,1,0],dtype=bool)

In [80]:
b=np.array([0,0,1],dtype=bool)

In [81]:
np.logical_or(a,b)

array([ True,  True,  True])

In [82]:
np.logical_and(a,b)

array([False, False, False])

In [86]:
#to check for all the values
np.all(a==a)

True

In [87]:
a=np.array([[1,2],[3,4]])

In [88]:
a

array([[1, 2],
       [3, 4]])

In [89]:
np.sum(a)

10

In [90]:
#column wise
np.sum(a,axis=0)

array([4, 6])

In [91]:
#row wise
np.sum(a,axis=1)

array([3, 7])

In [92]:
a.max()

4

In [93]:
#the index at whic maximum value is there
a.argmax()

3

In [94]:
a=np.arange(1,10)

In [96]:
np.shape(a)

(9,)

In [99]:
#this will add a new dimension to the array
a[:,np.newaxis].shape

(9, 1)

In [100]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])